demo_ecom_prjct/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('cart/<n>',views.addtocart,name="cart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('full_remove/<n>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),
]

demo_ecom_prjct/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('',include('search.urls')),
    path('',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demo_ecom_prjct/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('search',views.search,name='search'),

]

demo_ecom_prjct/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name='allcategories'),
    path('allproduct/<p>',views.allproducts,name="allproducts"),
    path('detail/<p>',views.detail,name="detail"),
    path('register',views.register,name='register'),
    path('login',views.userlogin,name='login'),
    path('logout',views.userlogout,name="logout"),

]

demo_ecom_prjct/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
from django.http import HttpResponse
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

demo_ecom_prjct/search/models.py
from django.db import models

# Create your models here.

demo_ecom_prjct/shop/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField(max_length=200)
    image=models.ImageField(upload_to="category",null=True,blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField(max_length=200)
    image=models.ImageField(upload_to="product",null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

demo_ecom_prjct/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

# Create your views here.
def cartview(request):
    total=0
    u=request.user
    cart = Cart.objects.filter(user=u)
    for i in cart:
        total+=i.quantity*i.product.price
    return render(request, 'cart.html',{'c':cart,'total':total})
@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
            cart.quantity+=1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if(p.stock>0):
            cart= Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()
    return cartview(request)
@login_required
def cart_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except:
        pass
    return cartview(request)

@login_required
def full_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)

        cart.delete()
    except:
        pass
    return cartview(request)

def orderform(request):
    if request.method == "POST":
        a = request.POST['a']
        ph = request.POST['ph']
        an = request.POST['an']
        u = request.user
        cart = Cart.objects.filter(user=u)
        total = 0
        for i in cart:
            total += i.quantity * i.product.price

            try:
                num=int(an)
                ac = Account.objects.get(acctnum=num)
                if ac.amount >= total:
                    ac.amount -= total
                    ac.save()
                    for i in cart:
                        o=Order.objects.create(user=u,product=i.product,address=a,phone=ph,no_of_items=i.quantity,order_status="paid")
                        o.save()
                    cart.delete()
                    msg="your order placed success"
                    return render(request, 'orderdetail.html', {'msg': msg})
                else:
                    msg = "insufficient amount.you can't place order"
                    return render(request, 'orderdetail.html', {'msg': msg})

            except Account.DoesNotExist:
                return HttpResponse("Account not found")
    return render(request,'orderform.html')

def orderview(request):
    u = request.user
    o=Order.objects.filter(user=u)
    return render(request, 'orderview.html',{'o':o,'u':u.username})

demo_ecom_prjct/search/views.py
from django.shortcuts import render
from django.db.models import Q
from shop.models import Product
# Create your views here.
def search(request):
    b= None
    q=""
    if(request.method == "POST"):
        q=request.POST['q']
        if q:
            b=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request,'search.html',{'q':q,'b':b})

demo_ecom_prjct/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})
def allproducts(request,p):
    c = Category.objects.get(name=p)
    p = Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})
def detail(request,p):
    p = Product.objects.get(name=p)
    return render(request,'detail.html',{'p':p})
def register(request):
    if (request.method == "POST"):
        n = request.POST['n']
        p = request.POST['p']
        cp = request.POST['cp']
        nf = request.POST['nf']
        nl = request.POST['nl']
        e = request.POST['e']
        if(p==cp):
            user = User.objects.create_user(username=n, password=p, first_name=nf, last_name=nl,email=e)
            user.save()
            return redirect('shop:allcategories')
        else:
            return HttpResponse("password same")
    return render(request, 'register.html')

def userlogin(request):
    if (request.method == 'POST'):
        n = request.POST['n']
        p = request.POST['p']
        user = authenticate(username=n,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcategories')
        else:
            return HttpResponse("invalid response")
    return render(request,'login.html')
@login_required
def userlogout(request):
    logout(request)
    return redirect('shop:login')

demo_ecom_prjct/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@1&family=Noto+Sans+JP:wght@100&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<style>
    header {
    background-color: #dbd7d5;
    }
    .clr{
     background-color: #dbd7d5;
    }

</style>
<body class="clr">
<header>
    <center><img src="{% static 'image/img.png' %}" class="" height="100px" width="300px"></center>
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary mt-2 mx-0">
  <div class="container-fluid">
    <a class="navbar-brand fs-3 fw-bold" href="#">Shopify</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link fs-5" aria-current="page" href="{% url 'shop:allcategories' %}">Home</a>
        </li>

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-5" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
             {% if user.is_authenticated %}
        </li>

          <li class="nav-item">
              <a class="nav-link fs-5" href="{% url 'shop:logout' %}">logout</a>
          </li>
          {% if user.is_superuser == False %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup class="ms-2">{{count}}</sup></a>
          </li>
          <li class="nav-item">
              <a class="nav-link fs-5" href="{% url 'cart:orderview' %}">Your orders</a>
          </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
              <a class="nav-link fs-5" href="{% url 'shop:register' %}">Register</a>
          </li>
          <li class="nav-item">
              <a class="nav-link fs-5" href="{% url 'shop:login' %}">login</a>
          </li>
          {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-light btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}

<footer class="footer fixed-bottom bg-secondary text-center" >
  <div class="container p-3">
      <p><b><i class="fa-solid fa-copyright"></i>MyShop Pvt ltd.All Rights Reserved</b></p>
  </div>
</footer>
</body>
</html>

demo_ecom_prjct/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h4 class="text-center">Shopping Cart</h4>
        <div class="col-6">
            <table class="table table-bordered">
                <tr class="p-3 mb-2 bg-primary text-white"><th>Cart Items</th></tr>
                {% for i in c %}
                <tr><td><img src="{{i.product.image.url }}" height="200px" width="400px"></td>
                <td>{{i.product.name}}</td>
                <td><h6>Product Id:{{i.product.id}}</h6>
                <h6>Unit Price:{{i.product.price}}</h6>
                <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6></td>
                <td>Subtotal:{{i.subtotal}}</td>
                <td>
                    {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:cart' i.product.name %}"><i class="fa-solid fa-circle-plus"></i></a>
                <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                    {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                    {% endif %}
                </td>
                </tr>

                {% endfor %}
            </table>
        </div>
        <div class="col-4"style="position:relative;margin">
            <table class="table table-bordered" style="margin-left:200px">
            <tr class="p-3 mb-2 bg-primary text-white">
                <th colspan="5">Check out</th></tr>
            <tr><td>total:{{total}}</td></tr></table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute;left:220px;">Place Order</a>
            <a href="{% url 'shop:allcategories' %}" class="btn btn-danger" style="margin-left:520px">Continue Shopping</a>
        </div>

    </div>
</div>
{% endblock %}

demo_ecom_prjct/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .demo {
        height: 70px; /* Set the desired height for the scrollable area */
        overflow-y: auto; /* Enable vertical scrollbar */
    }
</style>
<div>
    <img src="{% static 'image/img_1.png' %}" height="400px" width="100%">
</div><br>
<div class="container-fluid fs-3">
    <h3 class="text-center fw-bold fs-1">Our Collections</h3>
    <p  style="text-align:justify;padding:50px;">A website that allows people to buy and sell physical goods, services, and digital products over the internet rather than at a brick-and-mortar location.
    Through an e-commerce website, a business can process orders, accept payments, manage shipping and logistics, and provide customer service.</p>
</div>
<div class="container-fluid">
    <div class="row" style="padding-bottom:100px" >
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width:auto; height:auto;">
                <img src="{{i.image.url}}" class="card-img-top" alt="..." height="230px" >
                <div class="card-body">
                    <center><h5 class="card-title"><b>{{i.name}}</b></h5></center>
                    <div class="text-center">
                    <p class="card-text demo">{{i.desc}}</p>
                    <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary" style="width:200px;margin:auto; ">Products</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div>
    <img src="{% static 'image/img_2.png' %}" height="400px" width="100%">
</div><br><br><br><br>
{% endblock %}

demo_ecom_prjct/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="height:300px">
<div class="container-fluid card mb-3" style="max-width: 600px; padding:30px; margin-top:70px; margin-bottom:170px margin-left:350px; width:1000px; height:300px">
  <div class="container-fluid row g-0">
    <div class="col-md-4">
      <img src="{{p.image.url}}" class="img-fluid rounded-start" alt="..." style="height:170px">
    </div>
    <div class="col-md-8">
      <div class="card-body" >
        <h5 class="card-title">{{p.name}}</h5>
        <p class="card-text">{{p.desc}}</p>
        <p class="card-text"><small class="text-muted">{{p.price}}</small></p>

        {% if user.superuser == True %}
          {% if p.stock == 0 %}
            <h3>Out of Stock</h3>
            <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger">Add Stock</a>
          {% else %}
            <h3>Product in Stock</h3>
            <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger">Add Stock</a>
          {% endif %}
        {% else %}
          {% if p.stock == 0 %}
            <h3>Out of Stock</h3>
          {% else %}
            <a href="{% url 'cart:cart' p.name %}" class="btn btn-primary" style="width:200px; margin-left:50px;">ADD TO CART</a>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

demo_ecom_prjct/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="cotainer-fluid" style="margin-bottom:160px">
<center><h1>login Here..</h1></center>
<form method="POST" action="">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="n" placeholder="Enter the name">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter the password">
  </div>
  <center><button type="submit" class="btn btn-primary">Submit</button></center>
</form></div>
{% endblock %}

demo_ecom_prjct/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h4 class="text-center text-success">{{msg}}</h4>
    <h4 class="text-center text-danger">THANK YOU.</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcategories' %}">Continue Shopping</a></h4>
</div>

{% endblock %}

demo_ecom_prjct/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Order please!!!</h3>

  <form method="POST" style="padding:20px;">
    {% csrf_token %}
    <div class="mb-3">
      <label for="address" class="form-label">Address</label>
      <input type="text" class="form-control" id="address" name="a" placeholder="Enter the address">
    </div>
    <div class="mb-3">
      <label for="phone" class="form-label">Phone </label>
      <input type="text" class="form-control" id="phone" name="ph" placeholder="Enter the phone number">
    </div>
    <div class="mb-3">
      <label for="accountNumber" class="form-label">Account Number</label>
      <input type="number" class="form-control" id="accountNumber" name="an" placeholder="Enter the account number">
    </div>
      <div>
      <input type="submit" class="form-control btn btn-danger" >
    </div>
  </form>
</center>
{% endblock %}

demo_ecom_prjct/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<table class="table table-bordered">
    <tr><h1>Name of the Customer:{{user.username}}</h1></tr>

    <tr><th>product_name:</th>
        <th>product_price:</th>
        <th>delivery_address:</th>
        <th>phone:</th>
        <th>no_of_items:</th>
        <th>ordered on:</th>
        <th>delivery_status:</th>
    </tr>
    {% for i in o %}
    <tr>
        <td>{{i.product.name}}</td>
        <td>{{i.product.price}}</td>
        <td>{{i.address}}</td>
        <td>{{i.phone}}</td>
        <td>{{i.no_of_items}}</td>
        <td>{{i.ordered_date}}</td>
        <td>{{i.delivery_status}}</td></tr>
{% endfor %}
</table>
{% endblock %}

demo_ecom_prjct/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="400px" width="100%">
</div><br>
<div class="container-fluid fs-4 text-center">
    <h3 class="fw-bold fs-3">{{c.name}}</h3>
    <p style="text-align:center;padding:50px;">{{c.desc}}</p>
</div>
<div class="container-fluid">
    <div class="row" style="padding-bottom:100px">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width:auto; height:auto;">
                <img src="{{i.image.url}}" class="card-img-top" alt="..." height="230px" >
                <div class="card-body">
                    <center><h5 class="card-title"><b>{{i.name}}</b></h5></center>
                    <div class="text-center">
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="width:200px;margin-left:50px;">Products</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

demo_ecom_prjct/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="cotainer-fluid" style="margin-bottom:100px">
<center><h1>Register Here...</h1></center>
<form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">User name</label>
    <input type="text" class="form-control" name="n" placeholder="Enter the username">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter the password">
  </div>
  <div class="mb-3">
    <label class="form-label">Conform Password</label>
    <input type="password" class="form-control" name="cp" placeholder="Enter the confirm password">
  </div>
    <div class="mb-3">
    <label class="form-label">First name</label>
    <input type="text" class="form-control" name="nf" placeholder="Enter the Firstname">
  </div>
    <div class="mb-3">
    <label class="form-label">Last name</label>
    <input type="text" class="form-control" name="nl" placeholder="Enter the Lastname">
  </div>
    <div class="mb-3">
    <label  class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="Enter the email">
  </div>

  <center><button type="submit" class="btn btn-primary">Submit</button></center>
</form></div>
{% endblock %}

demo_ecom_prjct/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h4>searched query is :{{q}}</h4>
<div class="container">
    {% if b %}
    <div class="row justify-content-center" style="padding-bottom:100px">
        {% for i in b %}
        <div class="col-sm-4 ">
            <div class="card" style="width: 21rem;">
                <img src="{{i.image.url}}" class="card-img-top" alt="..." height="230px" >
                <div class="card-body">
                    <center><h5 class="card-title"><b>{{i.name}}</b></h5></center>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="width:200px;margin-left:50px;">Products</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div>
        <p>no result founded</p>
    </div>
    {% endif %}
</div>
{% endblock %}